import type { CodeHealthReport, RiskLevel } from './types.js';

function formatSeverity(severity: RiskLevel): string {
  if (severity === 'high') return 'High';
  if (severity === 'medium') return 'Medium';
  return 'Low';
}

function getScoreLabel(score: number): string {
  if (score >= 85) return 'Healthy';
  if (score >= 70) return 'Good';
  if (score >= 50) return 'Needs attention';
  return 'Critical';
}

export function generateMarkdownReport(report: CodeHealthReport): string {
  const riskyFiles = report.fileHealth
    .filter(file => file.riskLevel !== 'low')
    .sort((a, b) => b.lines - a.lines)
    .slice(0, 20);

  const recommendations = report.recommendations;

  return `# CodeHealth UA Report

## Project Summary

| Field | Value |
|---|---|
| Project | ${report.projectName} |
| Score | ${report.summary.score}/100 |
| Status | ${getScoreLabel(report.summary.score)} |
| Framework | ${report.projectMeta.framework} |
| Language | ${report.projectMeta.language} |
| Package manager | ${report.projectMeta.packageManager} |

---

## Health Score

| Category | Score |
|---|---:|
| Maintainability | ${report.summary.maintainability} |
| Testing | ${report.summary.testing} |
| Dependencies | ${report.summary.dependencies} |
| Project setup | ${report.summary.projectSetup} |

---

## Project Stats

| Metric | Value |
|---|---:|
| Source files | ${report.testHealth.sourceFiles} |
| Test files | ${report.testHealth.testFiles} |
| Test ratio | ${report.testHealth.testRatio} |
| Dependencies | ${report.packageHealth.dependenciesCount} |
| Dev dependencies | ${report.packageHealth.devDependenciesCount} |

---

## Package Health

| Check | Status |
|---|---|
| Build script | ${report.packageHealth.hasBuildScript ? 'Yes' : 'No'} |
| Test script | ${report.packageHealth.hasTestScript ? 'Yes' : 'No'} |
| Lint script | ${report.packageHealth.hasLintScript ? 'Yes' : 'No'} |
| TypeScript | ${report.packageHealth.hasTypeScript ? 'Yes' : 'No'} |
| ESLint | ${report.packageHealth.hasEslint ? 'Yes' : 'No'} |
| Prettier | ${report.packageHealth.hasPrettier ? 'Yes' : 'No'} |

---

## Risky Files

${
  riskyFiles.length > 0
    ? `| Risk | File | Lines | any | console.log | TODO/FIXME |
|---|---|---:|---:|---:|---:|
${riskyFiles
  .map(
    file =>
      `| ${formatSeverity(file.riskLevel)} | \`${file.file}\` | ${file.lines} | ${file.anyUsages} | ${file.consoleLogs} | ${file.todos} |`,
  )
  .join('\n')}`
    : 'No medium or high risk files detected.'
}

---

## Recommendations

${
  recommendations.length > 0
    ? recommendations
        .map(
          recommendation => `### ${formatSeverity(recommendation.severity)} — ${recommendation.title}

**Type:** ${recommendation.type}

${recommendation.message}

**Suggestion:** ${recommendation.suggestion}`,
        )
        .join('\n\n')
    : 'No recommendations generated.'
}

---

Generated by **CodeHealth UA**.
`;
}
